stages:
  - build

build_job:
  script:
    - vagrant up
    - vagrant destroy --force
  stage: build
  except:
    - /*-oasis-jessie$/

release_job:
  script:
    - vagrant up
    - vagrant destroy --force
  stage: build
  artifacts:
    paths:
      - ./data/*.zip 
  only:
    - /*-oasis-jessie$/
