stages:
  - build

build_job:
  script:
    - vagrant up
    - vagrant destroy --force
  stage: build
  except:
    - /v[0-9].*$/

release_job:
  script:
    - vagrant up
    - vagrant destroy --force
  stage: build
  artifacts:
    paths:
      - ./data/*.zip 
  only:
    - /[0-9]{4}-[0-1][0-9]-[0-3][0-9]-oasis-jessie$/
