stages:
  - build

build_job:
  script:
    - APT_PROXY=http://192.168.0.144:3142/archive.raspbian.org/raspbian vagrant up
    - vagrant destroy --force
  stage: build
  except:
    - /oasis-jessie$/

release_job:
  script:
    - APT_PROXY=http://192.168.0.144:3142/archive.raspbian.org/raspbian vagrant up
    - vagrant destroy --force
  stage: build
  artifacts:
    paths:
      - ./data/*.zip 
  only:
    - /oasis-jessie$/
