#!/bin/bash

for i in 1 2 3 4 5
do
        latest=$(wget -qO- https://s3-us-west-2.amazonaws.com/privacylabs-oasis-images/latest-system)
        if [ $? -eq 0 ]; then
                break
        else
                sleep 5
        fi
done

if [ -z $latest ]; then
        echo "unable to download latest-system version"
        exit -1
fi

latest_file=${latest##*/}
latest_date=$(echo $latest_file | cut -c1-10)
build_date=$(cat /etc/build_date)

date_current=$(date -d $build_date +"%Y%m%d")
date_latest=$(date -d $latest_date +"%Y%m%d")

if [ $date_latest -gt $date_current ]; then
        logger -s "Detected oasis system update.  Beginning update process."
        mkdir -p /data/cache/system
        if [ ! -f /data/cache/system/$latest_date-oasis-system* ]; then
                rm -f /data/cache/system/*.zip
                wget --directory-prefix=/data/cache/system --tries=10 $latest
                cd /data/cache/system && rm -f *.img && unzip $latest_file
        fi
        logger -s "Rebooting system to apply oasis system update."
        reboot
fi
