#!/bin/bash

if [ ! -d /var/log/nginx ]; then
        sudo mkdir /var/log/nginx
fi

if [ ! -d /var/log/redis ]; then
        sudo mkdir /var/log/redis
        sudo chown -R redis /var/log/redis
fi

if [ ! -d /data/cache/system ]; then
        sudo mkdir -p /data/cache/system
fi

sudo chmod 777 /data/cache/system
sudo rm -rf /data/cache/system/*

if [ ! -d /var/log/rspamd ]; then
	sudo mkdir /var/log/rspamd
	sudo chown -R _rspamd /var/log/rspamd
fi

if [ ! -d /var/log/caldavd ]; then
	sudo mkdir /var/log/caldavd
	sudo chown -R caldavd /var/log/caldavd
fi

CURRENT=2
VERSION=`cat /etc/fsversion`

if [ ! -f /etc/fsversion ]; then
	sudo rm -f /data/upper/etc/passwd
	sudo rm -rf /data/upper/usr
	sudo rm -rf /data/usr/lib

	echo 1 | sudo tee /etc/fsversion
	sudo reboot

fi	

if [ ! $VERSION == $CURRENT ]; then
	sudo systemctl stop postfix
	sudo chown -R postfix /var/lib/postfix
	sudo chown -R _rspamd /var/lib/rspamd
	sudo chown -R _rspamd /var/log/rspamd
	sudo chown -R opendkim /var/log/dkim-filter
	sudo chown -R redis /var/log/redis
	sudo chown -R redis /var/lib/redis
	sudo chown -R caldavd /var/log/caldavd
	sudo chown -R caldavd /etc/caldavd
	sudo chown -R caldavd /data/caldavd
	sudo chown -R postgres /var/log/postgresql
	sudo chown -R postgres /var/lib/postgresql
	sudo postfix set-permissions
	echo 2 | sudo tee /etc/fsversion
	sudo systemctl restart postfix
	sudo systemctl restart postgresql
fi
